apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexuszero-workers.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nexuszero-workers.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}