{{- range .Values.workers.statefulsets }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app.kubernetes.io/component: stateful-worker
    app.kubernetes.io/name: {{ .name }}
spec:
  serviceName: {{ $.Release.Name }}-{{ .name }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/component: stateful-worker
    spec:
      serviceAccountName: {{ include "nexuszero-workers.fullname" $ }}
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          command: {{ toJson .command }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $.Values.global.otelEndpoint | quote }}
            - name: REDIS_PRIVATE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.redisUrlSecretName }}
                  key: REDIS_PRIVATE_URL
            - name: DATABASE_PRIVATE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.global.databaseSecretName }}
                  key: DATABASE_PRIVATE_URL
          volumeMounts:
            - name: worker-cache
              mountPath: /var/lib/nexuszero/cache
          resources:
{{ toYaml .resources | indent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: worker-cache
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .storage.storageClassName }}
        resources:
          requests:
            storage: {{ .storage.size }}
---
{{- end }}